-- Legacy safarihost schema converted from MariaDB to PostgreSQL.
-- Generated by scripts/legacy-rebuild-from-dump.cjs
-- Encoding: UTF-8

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "topup_settlement_ledger" CASCADE;
DROP TABLE IF EXISTS "topup_orders" CASCADE;
DROP TABLE IF EXISTS "topup_order_events" CASCADE;
DROP TABLE IF EXISTS "top10wall" CASCADE;
DROP TABLE IF EXISTS "sub" CASCADE;
DROP TABLE IF EXISTS "storieview" CASCADE;
DROP TABLE IF EXISTS "storie" CASCADE;
DROP TABLE IF EXISTS "stats" CASCADE;
DROP TABLE IF EXISTS "site_master_wallet_ledger" CASCADE;
DROP TABLE IF EXISTS "site_master_wallet" CASCADE;
DROP TABLE IF EXISTS "site" CASCADE;
DROP TABLE IF EXISTS "settings" CASCADE;
DROP TABLE IF EXISTS "rooms" CASCADE;
DROP TABLE IF EXISTS "room_welcome_visits" CASCADE;
DROP TABLE IF EXISTS "profile_visits" CASCADE;
DROP TABLE IF EXISTS "powers" CASCADE;
DROP TABLE IF EXISTS "owner_agent_transfers" CASCADE;
DROP TABLE IF EXISTS "owner" CASCADE;
DROP TABLE IF EXISTS "notext" CASCADE;
DROP TABLE IF EXISTS "names" CASCADE;
DROP TABLE IF EXISTS "logs" CASCADE;
DROP TABLE IF EXISTS "intromsg" CASCADE;
DROP TABLE IF EXISTS "internal_mail" CASCADE;
DROP TABLE IF EXISTS "hosts" CASCADE;
DROP TABLE IF EXISTS "histletter" CASCADE;
DROP TABLE IF EXISTS "gift_notifications" CASCADE;
DROP TABLE IF EXISTS "followers" CASCADE;
DROP TABLE IF EXISTS "cuts" CASCADE;
DROP TABLE IF EXISTS "coin_packages" CASCADE;
DROP TABLE IF EXISTS "coin_ledger" CASCADE;
DROP TABLE IF EXISTS "bsb" CASCADE;
DROP TABLE IF EXISTS "bots" CASCADE;
DROP TABLE IF EXISTS "bars" CASCADE;
DROP TABLE IF EXISTS "band" CASCADE;
DROP TABLE IF EXISTS "agents" CASCADE;
DROP TABLE IF EXISTS "agent_wallets" CASCADE;
DROP TABLE IF EXISTS "agent_wallet_ledger" CASCADE;
DROP TABLE IF EXISTS "agent_payment_methods" CASCADE;

CREATE TABLE "agent_payment_methods" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "agent_id" bigint NOT NULL,
  "method_name" varchar(255) NOT NULL,
  "account_name" varchar(255) DEFAULT '',
  "account_identifier" varchar(255) DEFAULT '',
  "instructions" text DEFAULT NULL,
  "is_active" smallint DEFAULT 1,
  "sort_order" integer DEFAULT 0,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  CONSTRAINT "agent_payment_methods_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "agent_wallet_ledger" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "txid" varchar(128) DEFAULT '',
  "agent_id" bigint NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "amount" bigint NOT NULL,
  "before_balance" bigint NOT NULL,
  "after_balance" bigint NOT NULL,
  "actor_type" varchar(64) DEFAULT '',
  "actor_id" varchar(255) DEFAULT '',
  "counterparty_type" varchar(64) DEFAULT '',
  "counterparty_id" varchar(255) DEFAULT '',
  "note" text DEFAULT NULL,
  "reference_table" varchar(128) DEFAULT '',
  "reference_id" bigint DEFAULT 0,
  "created_at" bigint NOT NULL,
  CONSTRAINT "agent_wallet_ledger_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "agent_wallets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "agent_id" bigint NOT NULL,
  "balance_coins" bigint DEFAULT 0,
  "reserved_coins" bigint DEFAULT 0,
  "status" varchar(32) DEFAULT 'active',
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  CONSTRAINT "agent_wallets_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "agents" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(255) NOT NULL,
  "country_code" varchar(16) DEFAULT '',
  "city" varchar(255) DEFAULT '',
  "phone" varchar(64) DEFAULT '',
  "username" varchar(64) NOT NULL,
  "password_hash" text DEFAULT NULL,
  "status" varchar(32) DEFAULT 'active',
  "commission_type" varchar(32) DEFAULT 'spread',
  "commission_value" numeric(18,4) DEFAULT 0.0000,
  "can_receive_orders" smallint DEFAULT 1,
  "notes" text DEFAULT NULL,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  CONSTRAINT "agents_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "band" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name_band" varchar(255) DEFAULT NULL,
  "type" varchar(255) DEFAULT NULL,
  "deccode" varchar(255) DEFAULT NULL,
  "decoderDans" varchar(255) DEFAULT NULL,
  "device_band" varchar(255) DEFAULT NULL,
  "ip_band" varchar(255) DEFAULT NULL,
  "country_band" varchar(2) DEFAULT NULL,
  "date" varchar(255) DEFAULT 'دائم',
  CONSTRAINT "band_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "bars" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bcc" varchar(2000) DEFAULT '[]',
  "likes" varchar(2000) DEFAULT '[]',
  "bg" varchar(255) DEFAULT NULL,
  "bid" varchar(255) DEFAULT NULL,
  "lid" varchar(255) DEFAULT NULL,
  "mcol" varchar(255) DEFAULT NULL,
  "msg" text DEFAULT NULL,
  "pic" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "ucol" varchar(255) DEFAULT NULL,
  "uid" varchar(255) DEFAULT NULL,
  CONSTRAINT "bars_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "bots" (
  "idreg" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "msg" varchar(255) DEFAULT '(عضو جديد)',
  "pic" varchar(255) DEFAULT 'pic.png',
  "power" varchar(255) DEFAULT '',
  "country" varchar(255) DEFAULT '',
  "room" varchar(255) DEFAULT '',
  "ip" varchar(255) DEFAULT '',
  "id" varchar(255) DEFAULT '',
  "stat" integer DEFAULT 0,
  "topic" varchar(255) DEFAULT '',
  CONSTRAINT "bots_pkey" PRIMARY KEY ("idreg")
);

CREATE TABLE "bsb" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "systems" varchar(255) DEFAULT '',
  "browsers" varchar(255) DEFAULT '',
  CONSTRAINT "bsb_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "coin_ledger" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "txid" varchar(128) DEFAULT '',
  "event_type" varchar(64) NOT NULL,
  "actor_uid" varchar(255) DEFAULT '',
  "actor_idreg" integer DEFAULT 0,
  "user_uid" varchar(255) DEFAULT '',
  "user_idreg" integer DEFAULT 0,
  "counterparty_uid" varchar(255) DEFAULT '',
  "counterparty_idreg" integer DEFAULT 0,
  "amount" bigint NOT NULL,
  "before_balance" bigint NOT NULL,
  "after_balance" bigint NOT NULL,
  "gift_file" varchar(255) DEFAULT '',
  "note" text DEFAULT NULL,
  "ip" varchar(255) DEFAULT '',
  "created_at" bigint NOT NULL,
  CONSTRAINT "coin_ledger_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "coin_packages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(255) NOT NULL,
  "coins_amount" bigint NOT NULL,
  "price_local" numeric(18,4) DEFAULT 0.0000,
  "currency" varchar(16) DEFAULT '',
  "country_code" varchar(16) DEFAULT '',
  "city" varchar(255) DEFAULT '',
  "is_active" smallint DEFAULT 1,
  "sort_order" integer DEFAULT 0,
  "notes" text DEFAULT NULL,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  CONSTRAINT "coin_packages_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cuts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "text1" varchar(255) DEFAULT NULL,
  "text2" varchar(255) DEFAULT NULL,
  CONSTRAINT "cuts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "followers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "follower_id" varchar(255) NOT NULL,
  "following_id" varchar(255) NOT NULL,
  "created_at" bigint NOT NULL,
  CONSTRAINT "followers_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "gift_notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "txid" varchar(128) DEFAULT '',
  "to_uid" varchar(255) NOT NULL,
  "to_idreg" integer DEFAULT 0,
  "from_uid" varchar(255) DEFAULT '',
  "from_idreg" integer DEFAULT 0,
  "from_topic" varchar(255) DEFAULT '',
  "gift_file" varchar(255) DEFAULT '',
  "coin" bigint DEFAULT 0,
  "note" text DEFAULT NULL,
  "is_read" smallint DEFAULT 0,
  "created_at" bigint NOT NULL,
  "read_at" bigint DEFAULT 0,
  CONSTRAINT "gift_notifications_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "histletter" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ip" varchar(255) DEFAULT NULL,
  "msg" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "v" varchar(255) DEFAULT NULL,
  "time" varchar(255) DEFAULT NULL,
  "target" varchar(255) DEFAULT NULL,
  "source" varchar(255) DEFAULT NULL,
  "path" varchar(255) DEFAULT NULL,
  CONSTRAINT "histletter_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "hosts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "hostname" varchar(255) DEFAULT NULL,
  "setting" integer DEFAULT NULL,
  CONSTRAINT "hosts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "internal_mail" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "from_uid" varchar(255) NOT NULL,
  "from_username" varchar(255) DEFAULT '',
  "from_topic" varchar(255) DEFAULT '',
  "from_pic" varchar(255) DEFAULT '',
  "to_uid" varchar(255) NOT NULL,
  "to_username" varchar(255) DEFAULT '',
  "to_topic" varchar(255) DEFAULT '',
  "to_pic" varchar(255) DEFAULT '',
  "body" text DEFAULT NULL,
  "is_read" smallint DEFAULT 0,
  "created_at" bigint NOT NULL,
  "read_at" bigint DEFAULT 0,
  CONSTRAINT "internal_mail_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "intromsg" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "category" varchar(255) DEFAULT NULL,
  "adresse" varchar(255) DEFAULT NULL,
  "msg" varchar(255) DEFAULT NULL,
  CONSTRAINT "intromsg_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "state" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "username" varchar(255) DEFAULT NULL,
  "ip" varchar(255) DEFAULT NULL,
  "code" varchar(255) DEFAULT NULL,
  "device" varchar(255) DEFAULT 'en',
  "isin" varchar(255) DEFAULT NULL,
  "time" text DEFAULT NULL,
  CONSTRAINT "logs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "names" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "iduser" varchar(255) DEFAULT NULL,
  "fp" varchar(255) DEFAULT NULL,
  "ip" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "username" varchar(255) DEFAULT NULL,
  CONSTRAINT "names_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "notext" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" varchar(255) DEFAULT NULL,
  "path" varchar(255) DEFAULT NULL,
  "v" varchar(255) DEFAULT NULL,
  CONSTRAINT "notext_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "owner" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bars" smallint DEFAULT 1,
  "Vpn" smallint DEFAULT 0,
  "Gust" text DEFAULT NULL,
  "datafinish" timestamp DEFAULT CURRENT_TIMESTAMP,
  "MaxRep" integer DEFAULT 3,
  "Tv" text DEFAULT NULL,
  "Vistor" text DEFAULT NULL,
  "room" varchar(255) DEFAULT NULL,
  "isbanner" smallint DEFAULT 0,
  "rc" smallint DEFAULT 0,
  "cooment" smallint DEFAULT 0,
  "offline" smallint DEFAULT 0,
  CONSTRAINT "owner_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "owner_agent_transfers" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "txid" varchar(128) DEFAULT '',
  "agent_id" bigint NOT NULL,
  "coins_amount" bigint NOT NULL,
  "settlement_amount_local" numeric(18,4) DEFAULT 0.0000,
  "currency" varchar(16) DEFAULT '',
  "status" varchar(32) DEFAULT 'approved',
  "note" text DEFAULT NULL,
  "created_by" varchar(255) DEFAULT '',
  "approved_by" varchar(255) DEFAULT '',
  "created_at" bigint NOT NULL,
  "approved_at" bigint DEFAULT 0,
  CONSTRAINT "owner_agent_transfers_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "powers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "powers" text DEFAULT NULL,
  CONSTRAINT "powers_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "profile_visits" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "owner_id" varchar(255) DEFAULT NULL,
  "visitor_id" varchar(255) DEFAULT NULL,
  "visitor_name" varchar(255) DEFAULT NULL,
  "visitor_pic" varchar(255) DEFAULT NULL,
  "seen" integer DEFAULT 0,
  "time" bigint DEFAULT NULL,
  "visitor_type" varchar(20) DEFAULT 'عضو',
  CONSTRAINT "profile_visits_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "room_welcome_visits" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "room_id" varchar(255) NOT NULL,
  "identity_key" varchar(255) NOT NULL,
  "is_guest" smallint DEFAULT 0,
  "first_seen" bigint DEFAULT 0,
  "last_seen" bigint DEFAULT 0,
  "visits" integer DEFAULT 1,
  CONSTRAINT "room_welcome_visits_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "rooms" (
  "idroom" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "about" varchar(255) DEFAULT NULL,
  "user" varchar(255) DEFAULT NULL,
  "pass" varchar(255) DEFAULT NULL,
  "id" varchar(255) DEFAULT NULL,
  "owner" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "pic" varchar(255) DEFAULT NULL,
  "rmli" integer DEFAULT 0,
  "mic" integer DEFAULT 0,
  "welcome" varchar(255) DEFAULT NULL,
  "broadcast" smallint DEFAULT 0,
  "deleted" smallint DEFAULT 0,
  "needpass" smallint DEFAULT 0,
  "color" varchar(255) DEFAULT '#000000',
  "max" integer DEFAULT 0,
  "stage_count" integer DEFAULT 5,
  "stage_state" text DEFAULT NULL,
  "room_owner_meta" text DEFAULT NULL,
  "message_mode" varchar(16) DEFAULT 'real',
  CONSTRAINT "rooms_pkey" PRIMARY KEY ("idroom")
);

CREATE TABLE "settings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "site" text DEFAULT NULL,
  "dro3" text DEFAULT NULL,
  "them" text DEFAULT NULL,
  "cover" text DEFAULT NULL,
  "emo" text DEFAULT NULL,
  "sico" text DEFAULT NULL,
  "room_badges" text DEFAULT NULL,
  "site_badges" text DEFAULT NULL,
  "gifts_git" text DEFAULT NULL,
  "gift_categories" text DEFAULT NULL,
  CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "site" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "banner" varchar(255) DEFAULT NULL,
  "host" varchar(255) DEFAULT NULL,
  "ids" integer DEFAULT NULL,
  "logo" varchar(255) DEFAULT NULL,
  CONSTRAINT "site_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "site_master_wallet" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "site_id" integer NOT NULL,
  "balance_coins" bigint DEFAULT 0,
  "reserved_coins" bigint DEFAULT 0,
  "status" varchar(32) DEFAULT 'active',
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  CONSTRAINT "site_master_wallet_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "site_master_wallet_ledger" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "txid" varchar(128) DEFAULT '',
  "site_id" integer NOT NULL,
  "event_type" varchar(64) NOT NULL,
  "amount" bigint NOT NULL,
  "before_balance" bigint NOT NULL,
  "after_balance" bigint NOT NULL,
  "actor_type" varchar(64) DEFAULT '',
  "actor_id" varchar(255) DEFAULT '',
  "counterparty_type" varchar(64) DEFAULT '',
  "counterparty_id" varchar(255) DEFAULT '',
  "note" text DEFAULT NULL,
  "reference_table" varchar(128) DEFAULT '',
  "reference_id" bigint DEFAULT 0,
  "created_at" bigint NOT NULL,
  CONSTRAINT "site_master_wallet_ledger_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "stats" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "state" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "username" varchar(255) DEFAULT NULL,
  "room" varchar(255) DEFAULT NULL,
  "ip" varchar(255) DEFAULT NULL,
  "time" varchar(255) DEFAULT NULL,
  CONSTRAINT "stats_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "storie" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sid" varchar(255) DEFAULT '',
  "photo" varchar(255) DEFAULT '',
  "name" varchar(255) DEFAULT '',
  "link" varchar(255) DEFAULT '',
  "lastUpdated" varchar(255) DEFAULT '',
  "item" varchar(2000) DEFAULT '[]',
  "seen" smallint DEFAULT 0,
  "currentPreview" varchar(2000) DEFAULT '[]',
  CONSTRAINT "storie_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "storieview" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sid" varchar(255) DEFAULT '',
  "topic" varchar(255) DEFAULT '',
  "photo" varchar(255) DEFAULT '',
  "idsto" varchar(255) DEFAULT '',
  "item" integer DEFAULT 0,
  "time" text DEFAULT NULL,
  CONSTRAINT "storieview_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "sub" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "iduser" varchar(255) DEFAULT NULL,
  "sub" varchar(255) DEFAULT NULL,
  "topic" varchar(255) DEFAULT NULL,
  "topic1" varchar(255) DEFAULT NULL,
  "timestart" varchar(255) DEFAULT NULL,
  "timefinish" varchar(255) DEFAULT NULL,
  "timeis" varchar(255) DEFAULT NULL,
  CONSTRAINT "sub_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "top10wall" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "uid" varchar(255) DEFAULT '',
  "otype" varchar(255) DEFAULT '',
  "pic" varchar(255) DEFAULT '',
  "topic" varchar(255) DEFAULT '',
  CONSTRAINT "top10wall_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "topup_order_events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" bigint NOT NULL,
  "order_no" varchar(64) DEFAULT '',
  "event_type" varchar(64) NOT NULL,
  "old_status" varchar(32) DEFAULT '',
  "new_status" varchar(32) DEFAULT '',
  "actor_type" varchar(64) DEFAULT '',
  "actor_id" varchar(255) DEFAULT '',
  "note" text DEFAULT NULL,
  "created_at" bigint NOT NULL,
  CONSTRAINT "topup_order_events_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "topup_orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_no" varchar(64) NOT NULL,
  "user_uid" varchar(255) DEFAULT '',
  "user_idreg" integer DEFAULT 0,
  "user_topic" varchar(255) DEFAULT '',
  "user_username" varchar(64) DEFAULT '',
  "agent_id" bigint NOT NULL,
  "agent_code" varchar(64) DEFAULT '',
  "agent_name" varchar(255) DEFAULT '',
  "agent_phone" varchar(64) DEFAULT '',
  "agent_country_code" varchar(16) DEFAULT '',
  "agent_city" varchar(255) DEFAULT '',
  "package_id" bigint NOT NULL,
  "package_title" varchar(255) DEFAULT '',
  "package_coins" bigint NOT NULL,
  "package_price_local" numeric(18,4) DEFAULT 0.0000,
  "customer_price_local" numeric(18,4) DEFAULT 0.0000,
  "agent_profit_local" numeric(18,4) DEFAULT 0.0000,
  "agent_commission_type" varchar(32) DEFAULT 'spread',
  "agent_commission_value" numeric(18,4) DEFAULT 0.0000,
  "currency" varchar(16) DEFAULT '',
  "package_country_code" varchar(16) DEFAULT '',
  "package_city" varchar(255) DEFAULT '',
  "payment_method_id" bigint DEFAULT 0,
  "payment_method_name" varchar(255) DEFAULT '',
  "payment_method_account_name" varchar(255) DEFAULT '',
  "payment_method_identifier" varchar(255) DEFAULT '',
  "receipt_path" varchar(255) DEFAULT '',
  "receipt_uploaded_at" bigint DEFAULT 0,
  "payment_reference" varchar(255) DEFAULT '',
  "payment_note" text DEFAULT NULL,
  "status" varchar(32) DEFAULT 'pending',
  "processed_by" varchar(255) DEFAULT '',
  "processed_note" text DEFAULT NULL,
  "reject_reason" text DEFAULT NULL,
  "requested_at" bigint NOT NULL,
  "processed_at" bigint DEFAULT 0,
  "source_ip" varchar(255) DEFAULT '',
  "agent_commission_coins" bigint DEFAULT 0,
  CONSTRAINT "topup_orders_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "topup_settlement_ledger" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "txid" varchar(128) DEFAULT '',
  "order_id" bigint NOT NULL,
  "order_no" varchar(64) DEFAULT '',
  "event_type" varchar(64) NOT NULL,
  "agent_id" bigint DEFAULT 0,
  "agent_name" varchar(255) DEFAULT '',
  "user_uid" varchar(255) DEFAULT '',
  "user_idreg" integer DEFAULT 0,
  "package_id" bigint DEFAULT 0,
  "package_title" varchar(255) DEFAULT '',
  "package_coins" bigint DEFAULT 0,
  "currency" varchar(16) DEFAULT '',
  "customer_price_local" numeric(18,4) DEFAULT 0.0000,
  "site_share_local" numeric(18,4) DEFAULT 0.0000,
  "agent_profit_local" numeric(18,4) DEFAULT 0.0000,
  "processed_by" varchar(255) DEFAULT '',
  "note" text DEFAULT NULL,
  "created_at" bigint NOT NULL,
  CONSTRAINT "topup_settlement_ledger_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "users" (
  "idreg" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bg" varchar(255) DEFAULT '#FFFFFF',
  "mcol" varchar(255) DEFAULT '#000000',
  "ucol" varchar(255) DEFAULT '#000000',
  "evaluation" integer DEFAULT 0,
  "ico" varchar(255) DEFAULT '',
  "ip" varchar(255) DEFAULT '',
  "fp" varchar(255) DEFAULT '',
  "id" varchar(255) DEFAULT NULL,
  "lid" varchar(255) DEFAULT NULL,
  "uid" varchar(255) DEFAULT NULL,
  "msg" varchar(255) DEFAULT '(عضو جديد)',
  "pic" varchar(255) DEFAULT 'pic.png',
  "pich" varchar(255) DEFAULT 'pich.png',
  "power" varchar(255) DEFAULT '',
  "rep" bigint DEFAULT 0,
  "topic" varchar(255) NOT NULL,
  "username" varchar(50) NOT NULL,
  "password" varchar(255) NOT NULL,
  "token" varchar(255) NOT NULL,
  "youtub" varchar(255) DEFAULT '',
  "them" varchar(255) DEFAULT '',
  "cover" varchar(255) DEFAULT '',
  "loginG" smallint DEFAULT 0,
  "muted" smallint DEFAULT 0,
  "documentationc" integer DEFAULT 0,
  "lastssen" text DEFAULT NULL,
  "joinuser" text DEFAULT NULL,
  "site_badge_id" varchar(255) DEFAULT '',
  "site_badge" text DEFAULT NULL,
  "coins" bigint DEFAULT 0,
  "gift_ico" varchar(255) DEFAULT '',
  "gcol" varchar(255) DEFAULT '#FFFFFF',
  "last_eval_login_day" varchar(20) DEFAULT '',
  "auto_power" varchar(255) DEFAULT '',
  "wall_post_likes" bigint DEFAULT 0,
  "gifts_received_count" bigint DEFAULT 0,
  "eval_awards_json" text DEFAULT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("idreg")
);

CREATE INDEX "agent_payment_methods_idx_agent_payment_methods_agent" ON "agent_payment_methods" ("agent_id");
CREATE INDEX "agent_payment_methods_idx_agent_payment_methods_active" ON "agent_payment_methods" ("is_active");

CREATE INDEX "agent_wallet_ledger_idx_agent_wallet_ledger_agent" ON "agent_wallet_ledger" ("agent_id");
CREATE INDEX "agent_wallet_ledger_idx_agent_wallet_ledger_txid" ON "agent_wallet_ledger" ("txid");
CREATE INDEX "agent_wallet_ledger_idx_agent_wallet_ledger_created" ON "agent_wallet_ledger" ("created_at");

CREATE UNIQUE INDEX "agent_wallets_uniq_agent_wallets_agent_id" ON "agent_wallets" ("agent_id");
CREATE INDEX "agent_wallets_idx_agent_wallets_status" ON "agent_wallets" ("status");

CREATE UNIQUE INDEX "agents_uniq_agents_code" ON "agents" ("code");
CREATE UNIQUE INDEX "agents_uniq_agents_username" ON "agents" ("username");
CREATE INDEX "agents_idx_agents_status" ON "agents" ("status");
CREATE INDEX "agents_idx_agents_country" ON "agents" ("country_code");

CREATE INDEX "band_idx_band_device_band" ON "band" ("device_band");
CREATE INDEX "band_idx_band_ip_band" ON "band" ("ip_band");
CREATE INDEX "band_idx_band_country_band" ON "band" ("country_band");
CREATE INDEX "band_idx_band_decoderdans" ON "band" ("decoderDans");
CREATE INDEX "band_idx_band_name_band" ON "band" ("name_band");

CREATE INDEX "bars_idx_bars_bid" ON "bars" ("bid");
CREATE INDEX "bars_idx_bars_uid" ON "bars" ("uid");
CREATE INDEX "bars_idx_bars_lid" ON "bars" ("lid");
CREATE INDEX "bars_idx_bars_lid_bid" ON "bars" ("lid", "bid");

CREATE INDEX "bots_idx_bots_id" ON "bots" ("id");
CREATE INDEX "bots_idx_bots_room" ON "bots" ("room");
CREATE INDEX "bots_idx_bots_stat" ON "bots" ("stat");

CREATE INDEX "coin_ledger_idx_txid" ON "coin_ledger" ("txid");
CREATE INDEX "coin_ledger_idx_user_uid" ON "coin_ledger" ("user_uid");
CREATE INDEX "coin_ledger_idx_created_at" ON "coin_ledger" ("created_at");

CREATE INDEX "coin_packages_idx_coin_packages_active" ON "coin_packages" ("is_active");
CREATE INDEX "coin_packages_idx_coin_packages_country" ON "coin_packages" ("country_code");
CREATE INDEX "coin_packages_idx_coin_packages_sort" ON "coin_packages" ("sort_order");

CREATE INDEX "cuts_idx_cuts_text1" ON "cuts" ("text1");

CREATE UNIQUE INDEX "followers_follower_following" ON "followers" ("follower_id", "following_id");
CREATE UNIQUE INDEX "followers_idx_followers_pair" ON "followers" ("follower_id", "following_id");
CREATE INDEX "followers_idx_follower" ON "followers" ("follower_id");
CREATE INDEX "followers_idx_following" ON "followers" ("following_id");
CREATE INDEX "followers_idx_followers_follower" ON "followers" ("follower_id");
CREATE INDEX "followers_idx_followers_following" ON "followers" ("following_id");

CREATE INDEX "gift_notifications_idx_to_uid_read" ON "gift_notifications" ("to_uid", "is_read");
CREATE INDEX "gift_notifications_idx_created_at" ON "gift_notifications" ("created_at");
CREATE INDEX "gift_notifications_idx_txid" ON "gift_notifications" ("txid");
CREATE INDEX "gift_notifications_idx_gift_created_at" ON "gift_notifications" ("created_at");
CREATE INDEX "gift_notifications_idx_gift_txid" ON "gift_notifications" ("txid");

CREATE INDEX "histletter_idx_histletter_ip" ON "histletter" ("ip");
CREATE INDEX "histletter_idx_histletter_topic" ON "histletter" ("topic");

CREATE INDEX "hosts_idx_hosts_hostname" ON "hosts" ("hostname");
CREATE INDEX "hosts_idx_hosts_setting" ON "hosts" ("setting");

CREATE INDEX "internal_mail_idx_internal_mail_to_uid_read" ON "internal_mail" ("to_uid", "is_read");
CREATE INDEX "internal_mail_idx_internal_mail_to_uid_created" ON "internal_mail" ("to_uid", "created_at");
CREATE INDEX "internal_mail_idx_internal_mail_from_uid_created" ON "internal_mail" ("from_uid", "created_at");

CREATE INDEX "intromsg_idx_intromsg_category" ON "intromsg" ("category");

CREATE INDEX "logs_idx_logs_ip" ON "logs" ("ip");
CREATE INDEX "logs_idx_logs_time" ON "logs" (left("time"::text, 32));
CREATE INDEX "logs_idx_logs_state" ON "logs" ("state");
CREATE INDEX "logs_idx_logs_lookup" ON "logs" (left("ip"::text, 191), left("state"::text, 100), left("topic"::text, 100), left("username"::text, 100));

CREATE INDEX "names_idx_names_ip" ON "names" ("ip");
CREATE INDEX "names_idx_names_fp" ON "names" ("fp");
CREATE INDEX "names_idx_names_iduser" ON "names" ("iduser");
CREATE INDEX "names_idx_names_lookup" ON "names" (left("ip"::text, 191), left("fp"::text, 191), left("topic"::text, 100), left("username"::text, 100));

CREATE INDEX "notext_idx_notext_type" ON "notext" ("type");
CREATE INDEX "notext_idx_notext_path" ON "notext" ("path");

CREATE INDEX "owner_idx_owner_room" ON "owner" ("room");

CREATE INDEX "owner_agent_transfers_idx_owner_agent_transfers_agent" ON "owner_agent_transfers" ("agent_id");
CREATE INDEX "owner_agent_transfers_idx_owner_agent_transfers_txid" ON "owner_agent_transfers" ("txid");
CREATE INDEX "owner_agent_transfers_idx_owner_agent_transfers_created" ON "owner_agent_transfers" ("created_at");

CREATE INDEX "profile_visits_idx_profile_visits_owner" ON "profile_visits" ("owner_id");
CREATE INDEX "profile_visits_idx_profile_visits_visitor" ON "profile_visits" ("visitor_id");

CREATE UNIQUE INDEX "room_welcome_visits_uniq_room_identity" ON "room_welcome_visits" ("room_id", "identity_key");
CREATE INDEX "room_welcome_visits_idx_room_welcome_room" ON "room_welcome_visits" ("room_id");
CREATE INDEX "room_welcome_visits_idx_room_welcome_identity" ON "room_welcome_visits" ("identity_key");

CREATE INDEX "rooms_idx_rooms_id" ON "rooms" ("id");
CREATE INDEX "rooms_idx_rooms_owner" ON "rooms" ("owner");
CREATE INDEX "rooms_idx_rooms_topic" ON "rooms" ("topic");

CREATE INDEX "site_idx_site_ids" ON "site" ("ids");
CREATE INDEX "site_idx_site_host" ON "site" ("host");

CREATE UNIQUE INDEX "site_master_wallet_uniq_site_master_wallet_site_id" ON "site_master_wallet" ("site_id");

CREATE INDEX "site_master_wallet_ledger_idx_site_master_walle_3d7a57c" ON "site_master_wallet_ledger" ("site_id");
CREATE INDEX "site_master_wallet_ledger_idx_site_master_walle_966f016" ON "site_master_wallet_ledger" ("txid");
CREATE INDEX "site_master_wallet_ledger_idx_site_master_walle_fee7560" ON "site_master_wallet_ledger" ("created_at");

CREATE INDEX "stats_idx_stats_ip" ON "stats" ("ip");
CREATE INDEX "stats_idx_stats_room" ON "stats" ("room");
CREATE INDEX "stats_idx_stats_time" ON "stats" ("time");

CREATE INDEX "storie_idx_storie_sid" ON "storie" ("sid");

CREATE INDEX "storieview_idx_storieview_lookup" ON "storieview" ("idsto", "item", "sid");
CREATE INDEX "storieview_idx_storieview_sid" ON "storieview" ("sid");
CREATE INDEX "storieview_idx_storieview_idsto" ON "storieview" ("idsto");

CREATE INDEX "sub_idx_sub_iduser" ON "sub" ("iduser");
CREATE INDEX "sub_idx_sub_sub" ON "sub" ("sub");
CREATE INDEX "sub_idx_sub_timefinish" ON "sub" ("timefinish");

CREATE INDEX "top10wall_idx_top10wall_uid" ON "top10wall" ("uid");
CREATE INDEX "top10wall_idx_top10wall_uid_otype" ON "top10wall" ("uid", "otype");

CREATE INDEX "topup_order_events_idx_topup_order_events_order" ON "topup_order_events" ("order_id");
CREATE INDEX "topup_order_events_idx_topup_order_events_created" ON "topup_order_events" ("created_at");

CREATE UNIQUE INDEX "topup_orders_uniq_topup_orders_order_no" ON "topup_orders" ("order_no");
CREATE INDEX "topup_orders_idx_topup_orders_status" ON "topup_orders" ("status");
CREATE INDEX "topup_orders_idx_topup_orders_user_uid" ON "topup_orders" ("user_uid");
CREATE INDEX "topup_orders_idx_topup_orders_agent_id" ON "topup_orders" ("agent_id");
CREATE INDEX "topup_orders_idx_topup_orders_requested_at" ON "topup_orders" ("requested_at");

CREATE INDEX "topup_settlement_ledger_idx_topup_settlement_order" ON "topup_settlement_ledger" ("order_id");
CREATE INDEX "topup_settlement_ledger_idx_topup_settlement_txid" ON "topup_settlement_ledger" ("txid");
CREATE INDEX "topup_settlement_ledger_idx_topup_settlement_created" ON "topup_settlement_ledger" ("created_at");
CREATE INDEX "topup_settlement_ledger_idx_topup_settlement_agent" ON "topup_settlement_ledger" ("agent_id");

CREATE UNIQUE INDEX "users_username" ON "users" ("username");
CREATE INDEX "users_idx_users_uid" ON "users" ("uid");
CREATE INDEX "users_idx_users_lid" ON "users" ("lid");
CREATE INDEX "users_idx_users_token" ON "users" ("token");
CREATE INDEX "users_idx_users_ip" ON "users" ("ip");
CREATE INDEX "users_idx_users_fp" ON "users" ("fp");
CREATE INDEX "users_idx_users_topic" ON "users" ("topic");

