-- Normalized helper tables for the legacy safarihost schema.
-- Keeps legacy tables intact and adds query-friendly tables/indexes.
-- Encoding: UTF-8

CREATE TABLE IF NOT EXISTS bar_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id integer NOT NULL REFERENCES bars(id) ON DELETE CASCADE,
    legacy_bid varchar(255) DEFAULT '',
    author_topic varchar(255) DEFAULT '',
    author_pic varchar(255) DEFAULT '',
    body text NOT NULL DEFAULT '',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS bar_comment_replies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES bar_comments(id) ON DELETE CASCADE,
    legacy_cid varchar(255) DEFAULT '',
    author_topic varchar(255) DEFAULT '',
    author_pic varchar(255) DEFAULT '',
    body text NOT NULL DEFAULT '',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS bar_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id integer NOT NULL REFERENCES bars(id) ON DELETE CASCADE,
    identity varchar(255) NOT NULL DEFAULT '',
    uid varchar(255) DEFAULT '',
    lid varchar(255) DEFAULT '',
    idreg varchar(255) DEFAULT '',
    state integer DEFAULT 0,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS site_settings (
    key varchar(120) PRIMARY KEY,
    value jsonb NOT NULL DEFAULT '{}'::jsonb,
    source varchar(120) NOT NULL DEFAULT '',
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS site_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type varchar(40) NOT NULL,
    file_name varchar(255) NOT NULL DEFAULT '',
    file_url text NOT NULL DEFAULT '',
    sort_order integer NOT NULL DEFAULT 0,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS gift_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
  );

CREATE TABLE IF NOT EXISTS gifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar(255) DEFAULT '',
    name varchar(255) NOT NULL DEFAULT '',
    file_name varchar(255) NOT NULL DEFAULT '',
    file_url text NOT NULL DEFAULT '',
    coin bigint NOT NULL DEFAULT 0,
    category varchar(120) NOT NULL DEFAULT '',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS site_badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar(255) DEFAULT '',
    name varchar(255) NOT NULL DEFAULT '',
    background text NOT NULL DEFAULT '',
    icon_url text NOT NULL DEFAULT '',
    background_type varchar(40) NOT NULL DEFAULT 'static',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS room_badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar(255) DEFAULT '',
    name varchar(255) NOT NULL DEFAULT '',
    background text NOT NULL DEFAULT '',
    icon_url text NOT NULL DEFAULT '',
    background_type varchar(40) NOT NULL DEFAULT 'static',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_name varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    rank integer NOT NULL DEFAULT 0,
    icon_url text NOT NULL DEFAULT '',
    auto_enabled smallint NOT NULL DEFAULT 0,
    auto_promote smallint NOT NULL DEFAULT 0,
    auto_points integer NOT NULL DEFAULT 0,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_key varchar(120) NOT NULL,
    permission_value jsonb NOT NULL DEFAULT 'true'::jsonb,
    PRIMARY KEY (role_id, permission_key)
  );

CREATE TABLE IF NOT EXISTS user_role_assignments (
    user_idreg integer NOT NULL REFERENCES users(idreg) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    power_name varchar(255) NOT NULL DEFAULT '',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_idreg, role_id)
  );

CREATE TABLE IF NOT EXISTS story_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storie_id integer NOT NULL REFERENCES storie(id) ON DELETE CASCADE,
    item_index integer NOT NULL DEFAULT 0,
    itid varchar(255) DEFAULT '',
    item_type varchar(40) DEFAULT '',
    length_seconds integer DEFAULT 0,
    src text DEFAULT '',
    preview text DEFAULT '',
    link text DEFAULT '',
    link_text text DEFAULT '',
    item_time numeric,
    seen smallint DEFAULT 0,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb
  );

CREATE TABLE IF NOT EXISTS room_stage_state (
    room_idroom integer NOT NULL REFERENCES rooms(idroom) ON DELETE CASCADE,
    stage_number integer NOT NULL,
    state integer NOT NULL DEFAULT 0,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (room_idroom, stage_number)
  );

CREATE TABLE IF NOT EXISTS room_badge_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_idroom integer NOT NULL REFERENCES rooms(idroom) ON DELETE CASCADE,
    assignment_type varchar(40) NOT NULL DEFAULT 'assignment',
    user_idreg integer REFERENCES users(idreg) ON DELETE SET NULL,
    legacy_user_id varchar(255) DEFAULT '',
    username varchar(255) DEFAULT '',
    topic varchar(255) DEFAULT '',
    badge_legacy_id varchar(255) DEFAULT '',
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE INDEX IF NOT EXISTS bar_comments_bar_id_idx ON bar_comments (bar_id);
CREATE INDEX IF NOT EXISTS bar_comments_legacy_bid_idx ON bar_comments (legacy_bid);
CREATE INDEX IF NOT EXISTS bar_comment_replies_comment_idx ON bar_comment_replies (comment_id);
CREATE UNIQUE INDEX IF NOT EXISTS bar_likes_bar_identity_idx ON bar_likes (bar_id, identity);
CREATE INDEX IF NOT EXISTS bar_likes_uid_idx ON bar_likes (uid);
CREATE UNIQUE INDEX IF NOT EXISTS site_assets_type_file_idx ON site_assets (asset_type, file_name);
CREATE UNIQUE INDEX IF NOT EXISTS gift_categories_name_idx ON gift_categories (name);
CREATE UNIQUE INDEX IF NOT EXISTS gifts_legacy_id_idx ON gifts (legacy_id) WHERE legacy_id <> '';
CREATE INDEX IF NOT EXISTS gifts_category_idx ON gifts (category);
CREATE UNIQUE INDEX IF NOT EXISTS site_badges_legacy_id_idx ON site_badges (legacy_id) WHERE legacy_id <> '';
CREATE UNIQUE INDEX IF NOT EXISTS room_badges_legacy_id_idx ON room_badges (legacy_id) WHERE legacy_id <> '';
CREATE UNIQUE INDEX IF NOT EXISTS roles_legacy_name_idx ON roles (legacy_name);
CREATE INDEX IF NOT EXISTS roles_rank_idx ON roles (rank);
CREATE UNIQUE INDEX IF NOT EXISTS story_items_storie_item_idx ON story_items (storie_id, item_index);
CREATE INDEX IF NOT EXISTS story_items_itid_idx ON story_items (itid);
CREATE INDEX IF NOT EXISTS room_badge_assignments_room_idx ON room_badge_assignments (room_idroom);
CREATE INDEX IF NOT EXISTS room_badge_assignments_user_idx ON room_badge_assignments (user_idreg);

DROP INDEX IF EXISTS "followers_idx_followers_pair";
DROP INDEX IF EXISTS "followers_idx_followers_follower";
DROP INDEX IF EXISTS "followers_idx_followers_following";
DROP INDEX IF EXISTS "gift_notifications_idx_gift_created_at";
DROP INDEX IF EXISTS "gift_notifications_idx_gift_txid";
